README.md
as requested in #39, I reformatted the README and made this a separate PR against master
=> update README with graphviz, minor edits

app/controllers/qing_groups_controller.rb, app/models/ability.rb, config/routes.rb, spec/controllers/qing_groups_controller_spec.rb
http://redmine.sassafras.coop/issues/2076
=> Added crud for qing_group.

db/migrate/20130829010537_copy_mission_to_join_classes.rb
http://redmine.sassafras.coop/issues/2120
=> 2120 - migration fix

app/controllers/users_controller.rb, app/models/ability.rb, spec/controllers/users_controller_spec.rb, spec/models/ability/user_ability_spec.rb, spec/support/admin_abilities_in_mission_mode.rb, spec/support/admin_coordinator_shared_abilities.rb
http://redmine.sassafras.coop/issues/2101
=> fixed ability

Gemfile, Gemfile.lock, app/controllers/form_items_controller.rb, app/controllers/forms_controller.rb, app/models/form.rb, app/models/form_item.rb, app/models/form_versioning_policy.rb, app/models/questioning.rb, config/routes.rb, spec/controllers/form_items_controller_spec.rb, spec/models/condition_spec.rb, spec/models/form_item_spec.rb, spec/models/form_versioning_policy_spec.rb, test/factories/forms.rb
http://redmine.sassafras.coop/issues/2069
=> 2069 form items controller

.travis.yml, app/controllers/broadcasts_controller.rb, spec/controllers/broadcasts_controller_spec.rb
Got this working after some trial and error. It has two failing specs, but the same ones fail for me locally.
cf. https://travis-ci.org/thecartercenter/elmo/builds/64334800
=> 2372: Add Travis CI

app/controllers/missions_controller.rb, app/helpers/action_link_helper.rb
Also fixes a failure when viewing the forms view for a locked mission in mission mode.
=> 2342: Fix mission unlocking

Gemfile, Gemfile.lock, app/controllers/option_sets_controller.rb, app/helpers/action_link_helper.rb, app/models/option_node.rb, app/models/option_set.rb, app/views/option_sets/_form.html.erb, app/views/option_sets/export.xlsx.axlsx, app/views/users/form.html.erb, config/locales/en.yml, config/routes.rb
This PR adds the ability to export individual option sets as an XLSX spreadsheet.
=> 285: Option set XLS export

app/models/response.rb
Fix ported from release-4.16 branch
=> 2442: Avoid SQL error when Sphinx and MySQL are out of sync

app/models/condition.rb, app/models/itemsets_form_attachment.rb, app/models/option_node.rb, app/models/response.rb, spec/controllers/odk_submission_spec.rb, spec/models/condition_spec.rb
Porting fix from PR #81 from `release-4.16` to `develop` branch.
=> 2319: Fix optional required question submission via ODK

README.md
Just changed 'filing an bug report' to 'filing a bug report'.
=> Fix typo on section 'How Do I Contribute to ELMO'.

app/models/option_suggester.rb, spec/models/option_suggester_spec.rb
The problem was related to not escaping the query string.
=> 2684: Fix option suggest breaking with parenthesis.

app/assets/stylesheets/all/reset_password.css.scss
The problem was just a css that was overwriting the default styles for these kind of forms.
=> 2298: Fix reset password css styles.

app/assets/stylesheets/all/elmo_forms.css.scss, app/assets/stylesheets/all/option_sets.css.scss, app/views/option_sets/_option_levels.html.erb, app/views/option_sets/_options.html.erb
Just removed some custom css that was making it look strange and added styles to show an inline label -> input on the levels and option edit with latitude and longitude.
=> 2371: Fix styles on option sets modals.

Gemfile, Gemfile.lock, db/migrate/20150803165102_add_choice_foreign_key.rb, db/schema.rb, spec/controllers/options_controller_spec.rb
Had to fix previous migration (remove FK before adding it) because the staging database already have it. 
Also added gem to always keep schema ordered.
=> 2283 fix database schema

app/assets/javascripts/views/report/edit_pane.js
It wasn't setting the form_ids and, as a result, always showing all questions (Using ALL for the form_ids).
=> 2821: Call to extract was missing param.

app/helpers/odk_helper.rb, app/models/qing_group_fragment.rb, app/models/qing_group_odk_partitioner.rb, app/views/forms/_odk_group.xml.erb, app/views/forms/show.xml.erb, spec/models/qing_group_odk_partitioner_spec.rb
This was an issue with ODK rendering a multilevel question inside
a group. We had to remove it from the group when sending it to ODK
in order to keep it correct.
=> 2825 fix multilevel inside group odk

app/assets/javascripts/views/question_form.js, app/controllers/option_sets_controller.rb, app/models/option_set.rb, app/views/option_sets/_form.html.erb
Now we are disabling the option to be multilevel if it's creating an option set for a select multiple question.
=> 2846: Restrict option set multilevel creation on modal.

app/helpers/questions_helper.rb, app/views/questions/_min_max_condition.html.erb
It was just checking the wrong method on the partial. Created a helper
method to avoid these inconsistencies.
=> 2955: Fix maxmin strictly label on published questions.

app/controllers/upload_processable.rb
This was causing errors on user import, for example.
=> Add file extension on file upload.

app/controllers/concerns/report_embeddable.rb, app/controllers/reports_controller.rb, app/controllers/welcome_controller.rb, app/models/report/report.rb, app/views/welcome/_report_pane.html.erb
This is used on the welcome dashboard and when showing a separate
report.
=> 3229: Add low level caching for reports.

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/javascripts/controllers/report/report_controller.js, app/assets/javascripts/views/dashboard.js, app/assets/javascripts/views/dashboard_report.js, app/assets/javascripts/views/report_ajax_loader.js, app/assets/stylesheets/all/reports.css.scss, app/assets/stylesheets/all/welcome.css.scss, app/controllers/reports_controller.rb, app/controllers/welcome_controller.rb, app/views/reports/_main.html.erb, app/views/reports/show.html.erb, app/views/welcome/_report_pane_title.html.erb, app/views/welcome/dashboard.html.erb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/routes.rb
This change was done to improve load time on login and to show
the dashboard more quickly.
=> 3228: Make dashboard report use AJAX exclusively.

app/models/user.rb
Updates low activity query to properly constrain the results by mission id.
=> 3323: Fixes low activity users bug

app/helpers/answers_helper.rb
Fixes bug causing HTML tags to be displayed for answers to key questions
=> 3459: HTML Tags in Question

app/assets/javascripts/backbone/views/settings_view.js.coffee, app/controllers/settings_controller.rb, app/models/setting.rb, app/views/settings/index.html.erb
* Updates view with new 'Clear' checkboxes
* Updates backbone view with logic for checkboxes
* Fixes Setting model to incorporate logic
=> 3399: SMS Credentials Settings Fix

app/indices/answer_index.rb, app/models/answer.rb, app/models/response.rb
* Updates answer model with methods for option names
* Updates excerpt code to check option name fields
* Updates answer index to search associations
=> 3471: Adds searching on options and choices

app/controllers/responses_controller.rb, app/controllers/settings_controller.rb, app/helpers/csv_helper.rb, app/helpers/responses_helper.rb, app/models/answer.rb, app/models/form.rb, app/models/form_item.rb, app/models/option_set.rb, app/models/question.rb, app/models/response.rb, app/models/response_csv.rb, app/views/responses/index.csv.erb, app/views/settings/_external_sql.html.erb, app/views/settings/index.html.erb, config/initializers/inflections.rb, spec/controllers/responses_controller_spec.rb, spec/expectations/responses.csv, spec/factories/forms.rb, spec/factories/option_sets.rb, spec/factories/questions.rb, spec/factories/users.rb, spec/models/response_csv_spec.rb, spec/models/response_spec.rb, spec/support/option_node_support.rb
* Adds CSV to inflections
* Updates response model calls for export
* Creates ResponseCSV model to organize state for CSV generation
* Updates responses_to_csv code to use new ResponseCSV model
* Changes name of CSV helper to match new inflection
=> 1269: Response CSV format [WIP]

app/models/question.rb, app/models/response.rb, spec/models/search/question_search_spec.rb
* Changes several fields for search qualifiers to allow partial matching
=> 3468: Allow partial matches

app/mailers/admin_mailer.rb, app/views/admin_mailer/error.text.erb
* Adds hostname & rails environment to error reports
=> 2185: Adds hostname & rails environment on error

app/models/sms/decoder.rb, config/locales/en.yml
* Raises an error if the first answer token doesn't look like the start of an answer
=> 2962: Fixes SMS error when missing dot on first answer

app/controllers/tags_controller.rb
* fixes regression caused by issues with activemodel serializers
=> 4738: fixes broken tagging feature

app/assets/javascripts/legacy/views/report/table_display.js, app/models/concerns/report/gridable.rb, app/models/report/data.rb, app/models/report/list_report.rb, config/locales/en.yml
* Scales the limit for query based on number of questions
* Updates the display to indicate how many rows are omitted
* Fixes a bug in the JS detection for row counts on list report
=> 4819: fixes a weird issue with list reports

app/views/users/_login_instruction_box.html.erb, spec/models/report/answer_tally_report_spec.rb
Asked Roxana about what to display. She said only 'name' (not compact name) until Dottie asks for something else.
=> 5948 mission in print instructions

app/assets/stylesheets/all/components/_main.css.scss, app/assets/stylesheets/all/components/_settings.css.scss, app/controllers/settings_controller.rb, app/models/concerns/report/gridable.rb, app/models/report/grouping.rb, app/models/report/list_report.rb, app/models/response.rb, app/models/results/join.rb, app/models/results/sql_generator.rb, app/views/settings/_external_sql.html.erb, app/views/settings/index.html.erb, spec/models/results/sql_generator_spec.rb, spec/models/sms/sms_decoder_spec.rb
The spec failure is a very strange flapper. Runs fine individually.
=> 4957 external sql

app/assets/javascripts/legacy/views/question_form.js, config/locales/en.yml
This is a replacement for previous 5866 branch and PR because I rebased after Roxana had pulled it. This is an easy way for Roxana to pull updates and test.
=> 5866 opt set modal header v2

spec/models/response_csv_spec.rb
Try running Travis on a branch to see if the timezone issue is fixed.
=> 3016 fix test: try putting time zone setting into a before block.

app/controllers/operations_controller.rb, app/controllers/responses_controller.rb, app/controllers/welcome_controller.rb, app/models/assignment.rb, app/models/concerns/report/gridable.rb, app/models/operation.rb, app/models/operation_status.rb, app/models/response.rb, app/models/user.rb, spec/models/response_csv_spec.rb, spec/models/search/response_search_spec.rb, spec/models/user_spec.rb
This one turned out to be pretty simple. Just one reviewer is enough I think.
I cancelled the last test build b/c it was for a very small commit. I guess I shouldn't have but I feel bad for poor Travis working so hard all the time...
=> 6036 remove default scopes

app/controllers/users_controller.rb
Cleaning up the users controller filters was enough to fix this I think. (The problem was that the admin checkbox was getting ignored on create.)
We don't have great feature spec coverage here and I didn't have time to add some. But I tested new and edit in the following cases:
* Observer editing profile
* Mission mode (where even admins have permission to create/update users for that mission only)
* Admin mode
=> 6810: Refactored users controller to remove bug

app/assets/javascripts/components/ConditionsFormField.jsx, app/controllers/questionings_controller.rb
This has absolutely no styling work done on it, that should come with #7612
=> 7611: Delete Condition Draft

app/assets/stylesheets/all/components/_forms.css.scss, app/assets/stylesheets/all/components/_main.css.scss, app/assets/stylesheets/all/components/_sms_guide.css.scss, app/assets/stylesheets/print/_print.css.scss, app/assets/stylesheets/screen/_screen.css.scss
=> 7469: fixed float heading

app/helpers/application_helper.rb
=> 7994: added guard if error message is nil

app/models/old_answer_set.rb, app/views/responses/answers/_set.html.erb
=> 7488 add question code to responses show and edit

app/assets/stylesheets/print/_form.scss, app/views/qing_groups/_printable.html.erb, app/views/questionings/_printable.html.erb
I used a generic classname
As I am not fully familiar with the codebase, I didn't want to change too much too fast and risk breaking a styling I didn't even know existed
@smoyth
=> 8152 fix css

app/helpers/elmo_form_builder.rb, config/locales/en/main.yml, spec/features/user_form_spec.rb
=> 8412 add placeholders for phone numbers

app/decorators/response_decorator.rb, spec/decorators/response_decorator_spec.rb, spec/features/responses_index_spec.rb
Bug fixed in response decorator, added missing spec for response decorator, added spec for response listing
=> 8397 key question answers missing in responses index

.rubocop.yml, app/decorators/odk/form_item_decorator.rb, app/decorators/odk/qing_decorator.rb, app/decorators/odk/qing_group_decorator.rb, app/decorators/odk/subqing_decorator.rb, app/helpers/odk_helper.rb, app/models/itemsets_form_attachment.rb, app/models/odk/answer_parser.rb, app/models/odk/code_mapper.rb, app/models/odk/response_parser.rb, app/models/option_node.rb, spec/models/odk/code_mapper_spec.rb
Not sure about this style of PORO. Seems best to return form item id instead of item itself so errors happen mostly in parser, but we should talk about it.
=> 8602 refactor odk codes

app/models/form_item.rb, app/models/odk/response_parser.rb, app/models/report/answer_tally_report.rb, app/models/report/grouping.rb, app/models/response.rb, app/models/response_node.rb, app/models/results/blank_response_tree_builder.rb, app/models/results/join.rb, app/models/results/web_response_parser.rb, spec/decorators/answer_arranger_spec.rb, spec/decorators/response_decorator_spec.rb, spec/factories/responses.rb, spec/features/results/response_form_tree_handling_spec.rb, spec/models/choice_spec.rb, spec/models/report/summary_collection_multiple_spec.rb, spec/models/report/summary_collection_single_spec.rb, spec/models/report/truncation_spec.rb, spec/models/response_spec.rb, spec/models/response_tree_construction_spec.rb, spec/models/results/answer_instance_spec.rb, spec/models/results/answer_location_spec.rb, spec/models/results/csv/generator_spec.rb, spec/models/results/geopoint_processing_spec.rb, spec/models/results/sql_generator_spec.rb, spec/models/results/web_response_parser_spec.rb, spec/requests/responses_csv_spec.rb, spec/support/contexts/response_tree.rb, spec/support/helpers/model_spec_helpers.rb
Merge 8707 before looking at this diff. Branched off of 8707 (which has updates to response factory that are required for this issue)
=> 8646 v3 web response update

spec/models/form_spec.rb
I have updated the issue with notes about recreating the bug
This PR is just additional spec to cover deleting forms that have skip rules and some refactoring
=> 8450 form deletion bug

app/controllers/questions_controller.rb, spec/features/question_index_spec.rb
This fix is just for the question batch delete but when going through the app, I realized that the method that adds query strings to the redirect method is used in a lot of places in the system
=> 8659 question batch delete bug

app/controllers/option_set_imports_controller.rb, app/controllers/user_batches_controller.rb, app/helpers/operations_helper.rb, app/models/mission.rb, app/models/operation.rb, app/views/operations/show.html.erb, config/locales/en/main.yml, db/migrate/20181004181337_refactor_operations_to_have_mission_and_new_attributes.rb, db/schema.rb, spec/factories/operations.rb
For merging with attachment-as-operation work, need to rename operations attribute "description" to "details"
=> 8102 operations migration

config/database.yml.example, docs/development-setup.md
I encountered a few minor issues while setting up my local machine, namely the name of the dev database expected by database.yml and the existence of the `nemo_test` database.
=> Minor tweaks to dev-setup guide

app/models/answer.rb, app/models/option.rb, app/models/results/answer_search_vector_updater.rb, spec/models/option_spec.rb, spec/models/results/answer_search_vector_updater.rb, spec/models/results/answer_search_vector_updater_spec.rb
Fixes an issue where updating an option in an option set that is used in many many responses was crashing the server due to poor performance.
=> 9562 opt set update performance

app/views/responses/answers/_single_read_only.html.erb
=> 9644: Render barcode responses

app/assets/stylesheets/local/search/_filters.scss, app/javascript/components/search/Filters.js, app/javascript/components/search/FiltersModel.js, app/javascript/components/search/ReviewedFilter.js, app/javascript/components/search/utils.js, app/views/searches/_form.html.erb, config/locales/en/main.yml, package.json, spec/javascript/components/search/Filters.test.js, spec/javascript/components/search/ReviewedFilter.test.js, spec/javascript/components/search/__snapshots__/Filters.test.js.snap, spec/javascript/components/search/__snapshots__/ReviewedFilter.test.js.snap, spec/javascript/components/search/__snapshots__/utils.test.js.snap, spec/javascript/components/search/utils.js, spec/javascript/components/search/utils.test.js, yarn.lock
Main change:
- Added a "reviewed" search filter
Other major changes to be aware of:
- None
Related issues:
- Refactor to DRY up react components -- will do soon in https://redmine.sassafras.coop/issues/9624
- Secondary buttons have white text in ELMO theme -- upcoming PR to tackle this and other regressions from https://redmine.sassafras.coop/issues/9454
=> 9399 reviewed filter

app/assets/javascripts/views/user_login_instructions.js.coffee, app/assets/javascripts/views/user_profile_form_view.js.coffee, app/assets/stylesheets/local/users/_login_instructions.scss, app/controllers/users_controller.rb, app/javascript/components/search/AdvancedSearchFilter.js, app/javascript/components/search/FormFilter.js, app/javascript/components/search/QuestionFilter.js, app/javascript/components/search/ReviewedFilter.js, app/javascript/components/search/SubmitterFilter.js, app/views/users/_masked_value.html.erb, app/views/users/form.html.erb, app/views/users/login_instructions.html.erb, spec/features/login_instructions_spec.rb, spec/javascript/components/search/__snapshots__/AdvancedSearchFilter.test.js.snap, spec/javascript/components/search/__snapshots__/FormFilter.test.js.snap, spec/javascript/components/search/__snapshots__/QuestionFilter.test.js.snap, spec/javascript/components/search/__snapshots__/ReviewedFilter.test.js.snap, spec/javascript/components/search/__snapshots__/SubmitterFilter.test.js.snap
Fixed:
- Secondary buttons have white text on ELMO theme
- User password toggle doesn't work on new user info page
- On user edit, the password fields should only appear if you select "Enter a new password"
To-do:
=> 9712: Lingering BS4 regressions

app/decorators/odk/condition_decorator.rb, app/decorators/odk/form_decorator.rb, app/decorators/odk/qing_decorator.rb, app/models/condition.rb, app/models/questioning.rb, spec/decorators/odk/condition_decorator_spec.rb, spec/fixtures/odk/forms/allows_incomplete.xml, spec/fixtures/odk/forms/skip_rule_and_conditions.xml, spec/fixtures/odk/forms/various_question_types.xml, spec/models/condition_spec.rb
Updates the ODK XML rendering engine to support questioning references as the right side of a conditional expression.
=> 9693 q as ref support odk

app/assets/stylesheets/local/forms/_printable.scss, app/views/questionings/_printable.html.erb
[NEMO Sample Form [before codes].pdf](https://github.com/thecartercenter/nemo/files/3306880/NEMO.Sample.Form.original.pdf)
[NEMO Sample Form [after codes].pdf](https://github.com/thecartercenter/nemo/files/3306879/NEMO.Sample.Form.5.pdf)
=> 9782 print q codes

.travis.yml, app/javascript/components/Filters/SubmitterFilter/component.js, app/javascript/components/Filters/SubmitterFilter/component.test.js, app/javascript/components/Filters/SubmitterFilter/utils.js, app/javascript/components/Filters/component.test.js, app/javascript/components/Filters/injector.js, app/javascript/components/Filters/model.js, app/javascript/components/Filters/testUtils.js, app/javascript/components/Filters/utils.js, app/javascript/components/conditions/ConditionSetFormField/utils.js, app/javascript/components/conditions/DisplayLogicFormField/injector.js, app/javascript/components/conditions/SkipLogicFormField/SkipRuleSetFormField/SkipRuleFormField/injector.js
Mainly just making sure utils files don't import from non-utils files (should only import one-way to prevent cycles).
ESLint is also now run during CI.
=> 9836 circular deps

app/models/condition.rb, app/models/form.rb, app/models/form_item.rb, app/models/question.rb, spec/models/form_item_spec.rb, spec/models/form_spec.rb, spec/models/form_versioning_policy_spec.rb
Assigning assuming CI passes. I cancelled one of the builds b/c it was triggered due to a small typo. If the other one passes it should be fine. Thanks!
=> 9916 form destroy bug

app/controllers/concerns/condition_formable.rb, app/decorators/concerns/conditional_logic_decorable.rb, app/decorators/constraint_decorator.rb, app/decorators/odk/option_set_decorator.rb, app/decorators/odk/qing_decorator.rb, app/decorators/skip_rule_decorator.rb, app/helpers/sms_guide_helper.rb, app/models/concerns/translatable.rb, app/models/form_item.rb, app/views/forms/odk/_translation.xml.erb, app/views/forms/odk/_translation_group_node.xml.erb, app/views/forms/sms_guide.html.erb, spec/fixtures/odk/forms/conditional_logic.xml, spec/models/translatable_spec.rb, spec/requests/odk/form_rendering_spec.rb
Flapping specs seem to be failing, but the rest of this works for rendering to ODK.
=> 10151 show custom constraint rejection message

app/models/concerns/odk/mediable.rb, app/models/media/audio.rb, app/models/media/image.rb, app/models/media/video.rb, app/models/saved_tabular_upload.rb
I figured out why I used uppercase Z in #678 😉
=> Fix other usages of \Z => \z

.rubocop.yml, app/controllers/concerns/application_controller/authorization.rb, spec/requests/admin_mode_spec.rb, spec/requests/footer_spec.rb, spec/requests/logout_spec.rb, spec/requests/mission_change_redirect_spec.rb, spec/requests/response_checkout_spec.rb, spec/requests/sms/sms_console_spec.rb, spec/requests/user_form_spec.rb, spec/support/helpers/request_spec_helpers.rb
- Fixed error on redirect from questioning
- Added specs for every main route that can be redirected so this doesn't happen again
- Cleaned up old specs as discussed in pairing
=> 10311 fix questioning redirect on mission change

app/models/answer.rb, app/models/concerns/cacheable.rb, app/models/concerns/mission_based.rb, app/models/concerns/receivable.rb, app/models/concerns/report/gridable.rb, app/models/concerns/tree_traverseable.rb, app/models/odk/answer_parser.rb, app/models/odk/code_mapper.rb, app/models/odk/dynamic_pattern_parser.rb, app/models/odk/qing_group_partitioner.rb, app/models/odk/response_parser.rb, app/models/odk/user_config_encoder.rb, app/models/question.rb, spec/models/odk/code_mapper_spec.rb, spec/models/odk/rendering/qing_group_partitioner_spec.rb, spec/models/odk/user_config_generator_spec.rb, spec/models/results/csv/group_path_spec.rb, spec/models/results/web_response_parser_spec.rb
Split out of #683 for easier, separate review. Also easier to see which specs are affected.
=> 10327 remove old "q" support from CodeMapper

app/models/answer.rb, app/models/choice.rb, app/models/odk/answer_parser.rb, app/models/odk/code_mapper.rb, app/models/odk/response_parser.rb, app/models/results/web_response_parser.rb, spec/models/odk/code_mapper_spec.rb, spec/models/odk/response_parser_spec.rb, spec/models/results/web_response_parser_spec.rb
Ensure answers and option nodes don't refer to an item outside the current mission, for both web and ODK responses.
=> 10285 check correct mission

app/helpers/elmo_form_builder.rb, app/views/questionings/_form.html.erb, config/locales/en/main.yml
⚠️ TODO: Link to actual documentation, it may not exist yet?
=> 10325 hidden qing tweaks

app/assets/stylesheets/global/html_forms/_all_forms.scss, app/assets/stylesheets/global/html_forms/elmo_forms/_general.scss, app/views/forms/form.html.erb, app/views/option_set_imports/new.html.erb, app/views/responses/form.html.erb, app/views/user_imports/new.html.erb, app/views/user_sessions/new.html.erb
No visual changes, just causes the 'save' button to be the default action on enter key instead of 'save and publish'.
Also fixes similar issue with 'save and mark reviewed' for response edit.
=> 10441_fix_keyboard_enter_publish

.travis.yml
Testing config to make sure it works
=> Save 30 seconds CI by caching yarn install

app/controllers/qing_groups_controller.rb, spec/features/forms/form_item/display_logic_form_spec.rb, spec/features/forms/form_item/qing_group_form_spec.rb
`display_if` hadn't been permitted for `#update`. I manually tested quite a few other things and it all seems to work, it was just this one param.
=> 10703 display if any met

Gemfile.lock, app/models/ability.rb, app/overrides/o_data_controller_override.rb, config/initializers/inflections.rb, config/routes.rb, spec/requests/media/odk_response_spec.rb, spec/requests/odata/resource_spec.rb, spec/requests/odata/root_spec.rb, spec/requests/odk/form_download_spec.rb, spec/requests/odk/submission_spec.rb, spec/support/contexts/basic_auth.rb, spec/support/contexts/odata.rb
=> 10600: Add odata basic authorization

Gemfile, Gemfile.lock, app/models/o_data/simple_entity.rb, app/models/results/response_json_generator.rb, app/overrides/o_data_controller_override.rb, config/locales/en/main.yml, db/migrate/20200508155813_populate_response_cached_json.rb, spec/fixtures/odata/basic_metadata.xml, spec/fixtures/odata/empty_metadata.xml, spec/fixtures/odata/nested_groups_metadata.xml, spec/fixtures/response_json/legacy_group_now_repeat.json, spec/fixtures/response_json/legacy_repeat_now_group.json, spec/models/results/response_json_generator_spec.rb, spec/requests/odata/resource_spec.rb
Fixes for Power BI (for several scenarios with nested repeat groups), minor cleanup, and minor performance improvements.
=> 10597 - tweaks after manual testing

app/controllers/welcome_controller.rb, app/models/assignment.rb, app/views/welcome/_recent_responses.html.erb, app/views/welcome/_report_stats.html.erb, app/views/welcome/dashboard.html.erb
Overhauls dashboard caching to use low-level caching instead of fragment caching, following in the direction pioneered by @cooperka  :)
=> 11139: Overhaul caching on dashboard

app/models/o_data/simple_entities.rb, app/models/results/response_json_generator.rb, spec/fixtures/odata/basic_metadata.xml, spec/fixtures/odata/empty_metadata.xml, spec/fixtures/odata/nested_groups_metadata.xml, spec/fixtures/response_json/basic.json, spec/fixtures/response_json/legacy_group_now_repeat.json, spec/fixtures/response_json/legacy_new_qings.json, spec/fixtures/response_json/legacy_repeat_now_group.json, spec/fixtures/response_json/repeats.json, spec/requests/odata/resource_spec.rb
Minor tweak to make debugging easier, just confirming that specs pass.
=> Add LastCached datetime to odata json

config/application.rb
This was a separate bug I found, discussed in standup
=> 11297: Fix cache versioning setting

app/models/form.rb, app/models/odk/itemsets_form_attachment.rb, app/models/option_node.rb, db/migrate/20200930184702_rename_status_changed_at.rb, db/schema.rb, spec/factories/forms.rb, spec/models/form_spec.rb, spec/models/itemsets_form_attachment_spec.rb
=> 11101 some option set efficiencies

app/controllers/forms_controller.rb, app/decorators/action_links/form_link_builder.rb, app/views/forms/sms_guide.html.erb, config/locales/en/main.yml, spec/features/sms/sms_guide_spec.rb
1. Hide the link in index page and show/edit page if form is draft
2. Show a graceful error message if they visit the URL anyway
=> 10929 sms guide draft form

app/controllers/concerns/application_controller/error_handling.rb, app/controllers/concerns/application_controller/login_logistics.rb, config/locales/en/main.yml, spec/features/users/login_spec.rb, spec/support/helpers/feature_spec_helpers.rb
Verification steps: visit the login page and manually muck with the DOM, then try to sign in:
```html
<input type="hidden" name="authenticity_token" value="CHANGE_ME">
```
=> 11414: Gracefully handle InvalidAuthenticityToken

.idea/runConfigurations/db_migrate_redo_VERSION.xml, .rubocop.yml, app/models/media/object.rb, config/locales/en/operation.yml, db/migrate/20210322133526_rename_media_files_to_include_group.rb, db/schema.rb, spec/models/media/object_spec.rb, spec/models/odk/response_parser_spec.rb
=> 11617: Migration to update bulk media filenames

app/controllers/responses_controller.rb
When I originally wrote this, the checkbox parameters would not show up in the controller unless it was checked. So I'm not sure what happened here!
=> 11737: media download checkbox hotfix

app/controllers/forms_controller.rb, app/decorators/odk/form_decorator.rb, app/decorators/odk/option_set_decorator.rb, app/decorators/odk/qing_decorator.rb, app/models/odk/dynamic_pattern_parser.rb, app/models/odk/response_pattern_parser.rb, app/views/forms/odk/_instances.xml.erb, spec/decorators/odk/form_decorator_spec.rb, spec/fixtures/odk/forms/dynamic_values.xml, spec/models/odk/response_pattern_parser_spec.rb, spec/requests/odk/form_rendering_spec.rb
=> 11488 option val dynamic

app/controllers/operations_controller.rb, app/decorators/operation_decorator.rb, config/locales/en/main.yml
I copied the same way we paginate everything else; nothing special going on here.
Demo:
=> 11849: Paginate operations so it's not so slow

app/assets/javascripts/views/batch_actions_view.js, app/assets/javascripts/views/export_csv_view.js, app/assets/javascripts/views/response_list_view.js, app/controllers/responses_controller.rb, app/jobs/bulk_media_download_operation_job.rb, app/jobs/response_csv_export_operation_job.rb, app/models/results/csv/generator.rb, app/models/utils/bulk_media_packager.rb, app/views/responses/_export_csv_modal.html.erb, app/views/responses/index.html.erb, spec/features/responses/csv_export_spec.rb, spec/jobs/response_csv_export_operation_job_spec.rb, spec/models/results/csv/generator_spec.rb, spec/models/utils/bulk_media_packager_spec.rb
Well, the 8-year-old javascript helpers are dusty but it still works! Lemme know if you want to pair and I can explain chronologically how the data is flowing.
Please do test this manually if you have time, the DOM stuff is tricky!
=> 11881: Respect checkboxes when exporting CSV

app/models/user.rb
This is indeed best practice, though there are no current security issues with the old way.
Resolves #884
=> Update email/password validation to appease brakeman

.rubocop.yml, db/migrate/20220328224820_add_temp_processed_to_responses.rb, db/migrate/20220328224830_fix_partially_processed_responses.rb, db/migrate/20220328224840_remove_temp_processed_from_responses.rb, db/schema.rb, docs/production-setup.md
=> 12142 db migration to repopulate response data

app/helpers/application_helper.rb, app/models/results/response_json_generator.rb, app/overrides/o_data_controller_override.rb, spec/fixtures/odata/multilingual_metadata.xml, spec/requests/odata/metadata_spec.rb, spec/requests/odata/resource_spec.rb, spec/support/contexts/o_data.rb
Fixes the issue where metadata displays the english group name instead of whatever locale was specified as the mission default (but the response data uses the mission default, so Power BI can't handle the difference).
=> 12221 fix odata group i18n

app/controllers/responses_controller.rb, spec/features/responses/enketo_spec.rb
previously this was a hard error, now it works as expected
=> 12278: Force UTF-8 for converting enketo response to JSON

app/validators/forms/dynamic_pattern_validator.rb, config/locales/en/main.yml, spec/decorators/odk/form_decorator_spec.rb, spec/factories/questionings.rb, spec/validators/forms/dynamic_pattern_validator_spec.rb
Validates for both form "default name" and questioning "default answer".
Example:
=> 12196 validate usages of :value before saving

app/assets/stylesheets/global/_layout.scss, app/views/layouts/application.html.erb
=> 8990: Gray header color if in admin mode

app/assets/javascripts/views/form_items_draggable_list_view.js
https://github.com/thecartercenter/nemo/assets/4603869/755b7e72-6ea9-40ec-9e79-5a69e7971273
Tested with skip rules
=> 6366, 11820: Fix dragging up out of groups

app/models/form_item.rb, lib/tasks/form_rank_helpers.rake
to audit recent rank mismatch issue; requires more investigation.
=> Add form rank helpers scripts

.rubocop.yml
will merge if there are no hound errors
=> remove nonexistent ref to fix rubocop?

app/models/forms/export.rb
Fixes an edge case where conditions would not output correctly when option set node values are what is being conditioned upon
=> Fix relevant column not correctly displaying option set values

app/models/forms/export.rb
- Adds styling to header row
- ...
=> Improve human readability of XLSForm export
