app/controllers/concerns/application_controller/login_logistics.rb, config/locales/en.yml, config/locales/fr.yml
Following up #39 with a separate pull request against the develop branch:
When logging in as a newly-created admin user, you are redirected to the profile and password edit page. The user sees a flash message prompting them to enter a new password.
=> On first login, redirect admin to their password edit page

app/controllers/forms_controller.rb, app/controllers/responses_controller.rb, app/models/user.rb, db/migrate/20150422182449_remove_unassigned_users_from_whitelist.rb
<s>This PR changes the `User.assigned_to_or_admin` scope to only include admins who have submitted a response to a mission.</s>
Let me know if you want me to look at optimizing the queries in this scope; I'd possibly look at using a correlated subquery with `EXISTS`.
=> 2163: Only show admins in dropdown if they are the submitter of a response

Gemfile, Gemfile.lock, app/controllers/concerns/application_controller/authentication.rb, config/application.rb, config/environments/production.rb, config/environments/test.rb, config/initializers/rack-attack.rb, config/routes.rb, spec/requests/request_throttling_spec.rb
This PR implements the request throttling portion of issue 203 for the ODK Collect endpoints.
I haven't yet made it configurable, but that would involve using a `proc` for `:limit` (to ensure that the config has been fully loaded). Let me know if you actually want this to be configurable.
I also added a spec.
One thing I wasn't sure about was whether to make `direct_auth?` match paths without `.xml`. There are tests in `basic_authentication_spec.rb` that aren't using `.xml`, so I'm not sure what's actually being requested by ODK Collect. I also recall @hooverlunch mentioning that there is a potentially conflicting path for `/forms/:id`.
=> 203: Request throttling for ODK Collect endpoints

Gemfile, Gemfile.lock, app/controllers/user_sessions_controller.rb, app/helpers/captcha_helper.rb, app/views/user_sessions/new.html.erb, config/application.rb, config/initializers/local_config.rb.example, config/initializers/rack-attack.rb, config/initializers/recaptcha.rb, config/locales/en.yml
This PR enables support for requiring a reCAPTCHA when an excessive number of login attempts are made.
In the current implementation, both `GET` requests to `/xx/login` and all requests to `/xx/user-session/**` will count toward the threshold. Doing otherwise would require some sort of explicit check against the `rack-attack` tracking data stored in `Rack::Attack.cache`.
This will also need to be localized, particularly the `:verify_login` label on the login page and the reCAPTCHA itself (achievable with the `hl` parameter to `recaptcha_tags`).
=> 203: Require reCAPTCHA on excessive login attempts

spec/requests/incoming_sms_spec.rb
This is a quick and dirty conversion that keeps most of the existing `assert` calls instead of moving to `expect` style.
=> 2167: Incoming sms spec

Gemfile, Gemfile.lock, app/indices/answer_index.rb, bin/delayed_job, config/application.rb, config/deploy.rb, config/deploy/staging.rb, db/migrate/20150522175056_create_delayed_jobs.rb, db/schema.rb, docs/production-setup.md
This PR adds the [`ts-delayed-delta`](https://github.com/pat/ts-delayed-delta/) gem to allow Thinking Sphinx deltas to be processed via `delayed_job`.
I've also updated the Capistrano scripts to fix a couple bugs in `staging.rb` as well as to start DJ along with the main Nginx process.
=> 2215: Implemented delayed delta indexing

app/indices/answer_index.rb
Forgot to include this change in #67
=> 2215: Limit delayed job delta indexing to RAILS_ENV=production

app/assets/javascripts/response.js, app/controllers/responses_controller.rb, app/helpers/application_helper.rb, app/models/user.rb, app/views/layouts/application.html.erb, app/views/responses/form.html.erb, config/routes.rb, spec/features/responses_form_spec.rb, spec/support/capybara/select2_helper.rb
Uses the [Select2](https://select2.github.io/) library with remote data loading for the `Response.user_id` dropdown.
Also adds a `select2` helper for Capybara that should be able to replace `select` as needed.
=> 892: Scalable user selection

app/controllers/sms_controller.rb, app/models/sms/unverified_token_error.rb, config/environments/test.rb, spec/controllers/odk_submission_spec.rb, spec/requests/incoming_sms_spec.rb
By setting `config.action_dispatch.show_exceptions` to `false`, Capybara is able to recover the exception that caused a 500 error and show it in the console on test failure.
Turning off the `show_exceptions` flag turns off the default translation of a few exceptions like `ActiveRecord::RecordNotFound` into their corresponding HTTP status codes (e.g. 404 Not Found in the case of `ActiveRecord::RecordNotFound`). I've updated one spec to catch `ActiveRecord::RecordNotFound` instead of expecting a 404, but another approach later could be add an explicit `rescue_from` for `ActiveRecord::RecordNotFound`.
=> 2469: Make backtraces show up for feature spec failures

app/models/condition.rb, app/models/itemsets_form_attachment.rb, app/models/option_node.rb, app/models/response.rb, spec/controllers/odk_submission_spec.rb, spec/models/condition_spec.rb
Forms submitted through ODK while missing values that were conditionally required were being marked as incomplete. ELMO now trusts the `<ir01>` value submitted by the ODK client to detect incomplete responses and relies on the client correctly enforcing which answers are required.
This PR also fixes the handling of conditionally required questions in ODK, which appears to have broken in commit 3cc61489ba5ae0462eac37382b03e2c69fb9e9c0.
=> 2319: Fix detection of incomplete forms

Gemfile, Gemfile.lock, app/models/report/summary_collection_builder.rb, spec/models/report/summary_collection_single_spec.rb, spec/spec_helper.rb
I spent some time trying to create a test for this, but I wasn't able to figure it out in a reasonable amount of time. The `rspec-collection_matchers` gem was added to support an abortive attempt at testing the case where `qing_ids` has more than one value.
=> 2375: Fix blank values in report

app/assets/javascripts/backbone/views/answer_map_view.js.coffee, app/assets/javascripts/models/option_node.js, app/assets/javascripts/views/draggable_list.js, app/assets/javascripts/views/option_set_form.js, app/assets/stylesheets/all/option_sets.css.scss, app/assets/stylesheets/all/responses.css.scss, app/assets/stylesheets/screen/screen.css.scss, app/controllers/option_sets_controller.rb, app/models/answer.rb, app/models/choice.rb, app/models/option.rb, app/models/option_set.rb, app/models/report/answer_tally_report.rb, app/views/option_sets/_form.html.erb, app/views/option_sets/_options.html.erb, app/views/responses/_answer_map.html.erb, app/views/responses/_answer_read_only.html.erb, app/views/responses/_answer_set.html.erb, config/locales/en.yml, db/migrate/20150709233306_add_allow_coordinates_to_option_sets.rb, db/migrate/20150710212020_add_latitude_longitude_to_options.rb, db/schema.rb, spec/controllers/options_controller_spec.rb, spec/factories/choices.rb, spec/models/answer_spec.rb, spec/models/option_spec.rb
Adds the ability to mark a geographic `OptionSet` with an `allow_coordinates` flag. Setting this flag on an option set exposes the ability to edit the `latitude` and `longitude` fields of an associated `Option`.
For answers that have coordinates, a small map is now shown in the `Response` "show" view.
This PR contains a first pass at implementing coordinate validation in the option editing modal dialog. Since the existing implementation did not show any error messages, I have not added that ability here either. All I do is disable the "Save" button as was done previously.
=> 2337: Allow options to have geographic coordinates

app/controllers/option_sets_controller.rb, app/models/option.rb, app/models/option_node.rb, app/models/option_set.rb, config/locales/en.yml
Adds a "Coordinates" column to the `OptionSet` export if `allow_coordinates` is `true`. Also fixes the export of single-level option sets.
=> 2672: Add coordinates to geographic option set export

app/assets/javascripts/backbone/views/dashboard_map_view.js.coffee, app/controllers/welcome_controller.rb, app/models/answer.rb
This PR updates the `Answer. location_answers_for_mission` method to include answers to `select_one` and `select_multiple` questions with geographic coordinates if the associated `OptionSet` is marked to allow coordinates.
In addition, this PR also includes the yet-to-be-merged changes from #91 since they're necessary to support geographic `select_*` options at all.
=> 2338: Include geographic select_* answers on dashboard map

app/controllers/responses_controller.rb, app/views/responses/form.html.erb, config/locales/en.yml, db/migrate/20150714205221_add_reviewer_notes_to_response.rb, db/schema.rb, spec/features/responses_form_spec.rb
Reviewer notes are only visible to those with `:review` permission (i.e. admins and mission users with a level of staffer or higher).
=> 2397: Add reviewer notes field to Response

app/views/forms/sms_guide.html.erb
This PR adds a space for writing down the "User/Team" on the printable SMS guide.
It uses 7 `.answer_space` slots to avoid a wrapping problem that appears to be happening on `datetime`, `text`, and `long_text` fields (which use 8).
=> 2441: Add form field on SMS guide for User/Team

app/controllers/application_controller.rb, spec/controllers/odk_submission_spec.rb
Just added a conditional to `protect_from_forgery` to not do it if the request is not coming from the rails app (a json or xml format).
Also enabled the `protect_from_forgery` on the spec to mimic the application real behavior.
=> Fix bug 2706: Invalid authenticity token for /submission

docs/development-setup.md
The developer needs to use the random password that is generated when he executes the task `db:create_admin`. Before it was saying to use a `temptemp` password.
=> Change password instruction to login as admin.

app/models/condition.rb
Couldn't reproduce the bug, so we just decided to add an inspect
to better understand the problem next time it occurs.
=> 2705: Condition for select question has no option_ids.

app/helpers/odk_helper.rb, app/views/forms/_odk_group.xml.erb
The bug was happening because the partial `_odk_group` was trying to iterate over an empty `QingGroup`.
=> 2714: Fix problem with empty QingGroup on _odk_group.

app/controllers/concerns/question_formable.rb
The `key` attribute was being overwritten on the `init_qing` method. We decided to remove that part of the code because it was only being useful to set the `mission_id` (and that is being done on the lines below it).
=> 2674: Fix question key value not being set on save.

app/assets/stylesheets/all/rtl.css.scss
most elements in the UI look OK in a right-to-left language, but a few appear in the wrong order. Here's a SCSS file which flips the remaining lists and padding inside \<html dir="rtl"\>
=> CSS for right-to-left support

app/controllers/forms_controller.rb, app/models/form.rb
The problem reported was on form creation, where it wasn't saving the users on protected forms. But there was also a bug on edit. It wasn't removing whitelist_users because of a call on destroy instead
of destroy_all.
Also added dependent: :destroy on whitelist_users to avoid database orphans when we deleted a form.
=> 2275 fix whitelist users on protected form

config/thinking_sphinx.yml.example
It was just missing a configuration on the thinking_sphinx.yml.
For a while, Thinking Sphinx auto-escaped excerpts.However, Sphinx
itself can remove HTML entities for indexing and excerpts, which
is a better way to approach this.
=> 2280: Fix html showing on search results.

app/helpers/sms_helper.rb, config/locales/en.yml
The problem is that the string wasn't being tagged as `html_safe`. To avoid these kind of mistakes of just forgetting to call it, we can change the I18n key to end with "_html" and that automatically sets it as `html_safe`.
=> 2783: Fix <br> tag appearing on sms index.

app/models/search/qualifier.rb, app/models/search/token.rb, app/models/sms/message.rb, spec/models/search/search_spec.rb
Fixed bug of number:123 not searching sender of SMS. It turns out it was searching only on the .to column and not on the .from table also. 
Had to add support to generate a sql from multiple columns.
=> 2503: Add Search::Qualifier support for multi columns.

app/assets/stylesheets/all/elmo_forms.css.scss, app/assets/stylesheets/all/sms_guide.css.scss, app/assets/stylesheets/print/form.css.scss, app/helpers/elmo_form_helper.rb
It was just missing a `display: inline-block` on it's css. Also refactored class name to use dashes instead of underscore.
=> 2676: Fix required asterisk display on SMS guide.

app/views/forms/sms_guide.html.erb
For questions that were nested on a group, the ranks were being shown without the group index. Just created a helper to calculate and format that.
=> 2716: Fix questions numbering on sms guide.

app/helpers/questions_helper.rb
It wasn't being marked as html safe. We need to guarantee that the tag.name is being properly escaped
before doing this...
=> 2819: Fix tags not being rendered properly on form list.

app/models/sms/adapters/twilio_adapter.rb
Twilio doesn't support multiple recipients on the same call, so you need to iterate over each recipient to send a broadcast for more than one phone.
=> 2866: Fix sms broadcast not working with both phones.

app/models/replication/obj_proxy.rb, db/migrate/20150817204307_add_nullify_to_original_id_fks.rb, db/schema.rb, spec/models/replication/form_replication_spec.rb
The bug is related to duplicating a form more than once. After the first copy, each time you duplicate the original form again, it adds questionings copies to the first copy (on the form_items table) and not on the new copy.
Also added a nullify on original_id fk constraint, because user couldn't delete a form that was copied.
=> 2839 fix inconsistent qing count

app/models/concerns/translatable.rb, app/models/option_node.rb, app/models/option_set_import.rb, app/models/setting.rb, spec/models/option_set_import_spec.rb
Fix option set import preferred_locale and also export.
Import wasn't using the ones from configatron and export was just using the name for the option, not one
of it's translations. Now we are getting the translation for the first language preferred.
=> 2680 fix option set import/export i18n

docs/nginx.conf
nginx default is to allow only files with 1M.
=> Add client_max_body_size to allow bigger file uploads.

app/assets/javascripts/templates/report/form_summary_display.jst.ejs, app/models/report/standard_form_report.rb, app/models/user.rb, config/locales/en.yml, db/migrate/20150924200325_add_user_form_composite_index_on_responses.rb, db/schema.rb, spec/models/report/standard_form_report_spec.rb
The system was fetching all users to show them on the form. This was
making the system extremely slow when it had a lot of users on the
database. I created one query to fetch the users limiting how many
we are getting and used SQL_CALC_FOUND_ROWS to get the total count
without hitting the db again.
=> 3074: Improve non observers show on StandardFormReport.

app/assets/javascripts/views/report/table_display.js, app/models/concerns/report/gridable.rb, app/models/report/list_report.rb, app/models/report/response_tally_report.rb
This was done to avoid slowness when rendering a lot of table rows and on database fetching.
=> 3289: Limit reponses on ResponseTallyReport.

app/assets/javascripts/backbone/views/group_modal_view.js.coffee
Submitting the from with "enter" was both submitting the HTML form and triggering the save call in backbone causing the duplicate groups and the weird redirect.
=> 3014: Updates backbone view to prevent double form submission

app/models/option_set.rb, app/views/option_sets/export.xlsx.axlsx, spec/models/option_set_spec.rb
Fixes bug where option set names longer than 31 characters or with special characters would cause the export to fail.
* Adds `worksheet_name` method to OptionSet model
* Updates export view to use `worksheet_name` for the export
=> 3390: Fixes option set export bug

app/controllers/concerns/parameters.rb
Updates to multi-level option sets with read-only levels tried to permit child attributes that weren't present. This checks to make sure that the key for children to permit is present before continuing.
* Updates `permit_children` method in parameters concern with check for key presence
=> 3391: Fixes bug updating multilevel option sets

app/models/form.rb, app/models/questioning.rb, app/models/sms/decoder.rb, app/views/forms/sms_guide.html.erb, spec/models/sms/sms_decoder_spec.rb
* Makes `smsable_questionings` return an indexed hash
* Changes questionings object in SMS decoder to `smsable_questionings` hash
* Prints smsable_questionings index in SMS guide
=> 3007: Question groups are SMS-Able

app/controllers/application_controller.rb, app/controllers/concerns/application_controller/error_handling.rb, spec/controllers/odk_submission_spec.rb, spec/features/questions_flow_spec.rb
This will not send emails to admins for record not found. Tested manually that without changes, an email is sent on an ActiveRecord::RecordNotFound error and with changes, the email is not sent. Instead it just renders nothing with status 404. It also has a rescue block for InvalidAuthenticityToken but this is not tested. We'll see if the emails stop in production.
=> 5961 dont notify admin for 404

app/models/answer.rb, app/models/questioning.rb, app/models/response_csv.rb, spec/decorators/answer_arranger_spec.rb, spec/expectations/response_csv/repeat_groups.csv, spec/factories/forms.rb, spec/models/response_csv_spec.rb, spec/models/sms/sms_decoder_spec.rb
I made ‘repeat group’ more generic to just ‘group’ to handle non-repeat groups. Move ‘Group Name’ and ‘Group Level’ columns to the left, after the submission id, so that their position is consistent in exports with multiple forms.
=> 6148 repeat headers csv

app/models/user.rb, app/views/users/_reset_password_method.html.erb, app/views/users/form.html.erb, config/locales/en.yml, spec/factories/users.rb, spec/requests/user_management_spec.rb
Print option is only visible when not in admin mode and (you are making a new user or editing a user who is only an observer). When creating a new user outside of admin mode, validation will flash error if try to print instructions for non observer. 
There is still a rare use case that an admin assigns a user as observer in mission A and staffer in mission B, and a coordinator for mission A goes to try to print out a reset password for observer, and the coordinator won't see the option to print & won't know why. The hint is still pretty long & unwieldy. Should I add a different hint if a user isn't 'observer_only?'
=> 5917 print only for observers

app/controllers/responses_controller.rb, app/decorators/answer_arranger.rb, app/models/response.rb, spec/decorators/answer_arranger_spec.rb, spec/factories/responses.rb, spec/models/answer_instance_spec.rb
This PR refactors AnswerArranger to allow finer grained control over what placeholders get inserted when answer structure is being built. It's so we can show a blank non-repeat group in show mode, but not a blank repeat group, per Dottie's request.
=> 6843: Refactored AnswerArranger 

app/views/layouts/application.html.erb, config/locales/ar.yml
Last year before there was an Arabic locale, I added some CSS which supports right-to-left language layout: #131 
This would add a field to the locale file, allowing Arabic and other languages to set the dir attribute on the top-level HTML element.
Default value is dir=ltr
=> use dir=rtl on Arabic pages

app/decorators/odk/qing_group_decorator.rb, app/helpers/odk_helper.rb, app/models/form.rb, app/models/form_item.rb, app/models/forms/condition_computer.rb, app/models/forms/condition_group.rb, app/models/skip_rule.rb, app/views/forms/odk/_binding_node.xml.erb, spec/expectations/odk/forms/group_form.xml, spec/models/forms/condition_computer_spec.rb, spec/requests/form_odk_rendering_spec.rb
Adds ConditionComputer and specs and supporting classes.
Also adds support for display conditions on groups for ODK form rendering. This was a cleaner way to apply skip rules (skip the whole group with one computed condition instead of adding computed conditions to every single member of the group). It's also a nice feature that we really should have separate from this. I also created issues for adding condition capability to groups in other areas (e.g. web responses, form builder).
=> 7180 computed conditions

app/assets/javascripts/views/questioning_form_view.js.coffee, spec/features/questionings_form_spec.rb
Story says "Show required iff not readonly and metadata is blank." Problem: this is not a case because readonly is only available if a question type is defaultable, and only text questions are defaultable, and metadata is not available for text questions.
=> 8064 2 questioning form logic updates

app/assets/stylesheets/local/responses/hierarchical_form/_question_types.scss, app/views/responses/answers/_single_read_only.html.erb
It used to be a float, but thought it would be better just inline, rather than to the right. See before and after.
Before:
After:
=> 9150: reworked the map position in a geographic response

app/javascript/components/DisplayLogicFormField.js, app/javascript/components/SkipLogicFormField.js, app/javascript/components/SkipRuleFormField.js, app/javascript/components/SkipRuleSetFormField.js
Strange this fix was so easy, I repro'd it on v9.10 so I figured it would be something more than this.
Also includes a small cleanup of all React components to make sure the vars saved into `state` are actually changed by `setState`; otherwise keep them in `props` for clarity.
=> 9700: Don't allow filtering by the current question

app/assets/javascripts/views/settings_view.js.coffee, app/assets/javascripts/views/using_incoming_sms_token_view.js.coffee, app/views/settings/index.html.erb, app/views/users/form.html.erb, config/locales/en/main.yml, spec/features/settings/settings_regenerable_field_spec.rb, spec/features/users/user_form_spec.rb, spec/features/users/user_regenerable_field_spec.rb, spec/requests/api_key_field_spec.rb, spec/requests/sms_auth_code_field_spec.rb, spec/support/contexts/regenerable_fields.rb, spec/support/helpers/feature_spec_helpers.rb
=> 9540: Add warnings when regenerating keys

app/assets/javascripts/legacy/url_builder.js, package.json
To allow deploy. See commit messages for details.
Changes to `url_builder` are from this revert point: https://github.com/thecartercenter/nemo/blob/af33ed863b2479471b5d9517b408f7e28c135227%5E/app/assets/javascripts/legacy/url_builder.js.
Deployed successfully on staging.
=> 9722 fix assets:precompile in prod

app/javascript/components/Filters/FilterOverlayTrigger/__snapshots__/component.test.js.snap, app/javascript/components/Filters/FilterOverlayTrigger/component.js, app/javascript/components/Filters/FilterOverlayTrigger/component.test.js, app/javascript/components/Filters/model.js, app/javascript/components/conditions/ConditionSetFormField/model.js
Integration tests still coming soon after user-facing changes :)
Changes in this PR:
- Submit search automatically on dismiss popover
- Only if something has been modified
- In the case of the question filter, there's so much data to filter through it just makes a conservative judgment by deep-comparing the `conditions` array. If, for example, you change the condition and then revert it back, the conservative check will still assume something changed because of differing internal IDs and other modified metadata. Given the work required to do a full and accurate equality check, I say "good enough" to the conservative comparison.
=> 9623 apply filter on dismiss

app/javascript/components/Filters/QuestionFilter/component.js, app/javascript/components/Filters/utils.js, app/javascript/components/conditions/ConditionSetFormField/ConditionFormField/model.js, app/searchers/responses_searcher.rb, package.json, spec/searchers/responses_searcher_spec.rb, yarn.lock
Bug description:
> If you filter by a form, then ALSO filter by a cascading question, then ALSO submit the search a third time WITHOUT opening the question popover first, the question value is `Unknown` and the search fails.
This PR:
- Fixes the bug by filtering `qings` by any selected `form_id`s before determining the `refableQing` ID to pass to the client
- Does some minor code cleanup
This is the last remaining piece needed before releasing the initial version of filters.
=> 9945 cascading select filter bug

app/controllers/concerns/report_embeddable.rb, app/controllers/filter_data_controller.rb, app/models/question.rb, app/models/question_type.rb, app/models/questioning.rb
Only allow filtering by reportable questions (e.g. don't show images, audio, etc. as refableQings for the question search filter).
~~@smoyth you mentioned something in the call today about using `ref`, but I didn't see how that worked here. I had already come up with this solution, so submitting for feedback. Let me know if you prefer something else.~~
=> 9909 filter media types

app/assets/javascripts/legacy/views/mission_change_dropdown.js
Uses [`URLSearchParams`](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) to build, modify, and stringify the url params without the `search` query.
Note: Normally I'd use the more conventional npm `query-string` lib for this but it seems like the legacy JS code wouldn't deal well with that. This should be a robust solution, as far as I know. Related SO question [here](https://stackoverflow.com/a/901144/763231) as well.
=> 9958: Stop preserving search query between missions

spec/features/search/question_search_spec.rb, spec/features/search/response_search_spec.rb, spec/support/contexts/search.rb
They've been a long time coming but they're finally here 🎊 
These integration tests confirm that:
- The filters are active on the responses page (but not the questions page)
- The filters parse search strings and display them using the UI
- The filters display hints
- The select2 fields can be cleared
- The filters submit automatically on dismiss popover
They're intended to be high-level and not comprehensive (e.g. there's no specific integration spec for choosing a question with the dropdowns since that's covered in more specific tests), but let me know if you think I should cover more cases or if I missed anything.
=> 9775 filter integration specs

app/assets/stylesheets/global/_layout.scss
Quick win I came across. On smaller screens the logo wraps down and covers up the operations link. Nothing within/underneath the highlighted box below is clickable:
=> 9987: Don't obstruct other header links with logo

app/jobs/tabular_import_operation_job.rb, spec/factories/saved_uploads.rb, spec/jobs/tabular_import_operation_job_spec.rb
No error messages were being shown to the user for failed tabular import operations (at `/en/m/:mission/operations/:id`). Now they're back, e.g.
```
Error Report
Row 2: Main Phone: Please enter at least 9 digits.
Row 2: Alternate Phone: Please enter at least 9 digits.
```
Most recent related change seems to be https://github.com/thecartercenter/nemo/pull/583, for context -- specifically a change where `run_errors` were saved separately but not updated in this file.
New `tabular_import_operation_job_spec` was inspired by related `user_import_spec`.
=> 9991 tabular import errors

app/models/condition.rb, app/models/form_item.rb, app/models/form_logical.rb, app/models/question.rb, app/models/skip_rule.rb, spec/models/form_spec.rb
Added `touch: true` and callbacks to ensure creating, updating and deleting QingGroups, Questionings and Questions updated the `updated_at` timestamp on related forms.
=> #9899: Form "last modified" time should update when adding/modifying questions.

app/mailers/notifier.rb, spec/mailers/notifier_spec.rb
Only send emails to active users or admins when an SMS token is changed for a mission.
=> 9766 - Only email active users on SMS token change.

.babelrc, config/webpack/environment.js, config/webpacker.yml, package.json, yarn.lock
Moving to Webpacker 4 forced a move to Babel 7, which broke a number of JavaScript package usages.
=> Updates to fix issues moving to Webpacker v4.

app/controllers/filter_data_controller.rb, app/models/form_item.rb
Notes:
- Flapping started somewhere within https://github.com/thecartercenter/nemo/pull/617 (can't bisect precisely, not all commits compile, but somewhere in that range)
- The spec deterministically flaps **every other time it's run**, no matter what the seed value is
I'd prefer to do a more specific fix but I can't tell where `path` is actually getting set and it's too generic to search for. If you'd like to dive in feel free, but this fixes the flap and seems like a reasonably safe change.
=> 9957 flapping reviewer notes spec

app/jobs/response_csv_export_operation_job.rb
Removing ELMO from filename for response CSV exports. This may need to happen for option sets as well, but it isn't clear if/where that is happening.
=> 10222: Removing `elmo-` from response CSV export filename.

app/models/ability.rb, spec/models/ability/form_ability_spec.rb, spec/models/ability/question_ability_spec.rb, spec/models/ability/questioning_ability_spec.rb, spec/models/ability/response_ability_spec.rb, spec/models/ability/user_group_ability_spec.rb
As-is, this change allows ALL users to use the new filters UI. The reported issue mentioned staffers not being able to view groups, but the bug also affected all non-coordinators and also applied to the user dropdown.
If this is too permissive or you'd like additional test coverage, let's chat.
=> 10173 filter ui abilities

app/models/constraint.rb, db/migrate/20191009175040_remove_null_rejection_msg_constraint.rb, db/schema.rb, spec/factories/constraints.rb, spec/models/constraint_spec.rb
rejection_msg_translations already had a default, but was being set to `nil` due to empty strings for every locale.
=> 10225: Fix nil rejection_msg_translations issue

app/views/sms_tests/new.html.erb, spec/features/sms/sms_console_spec.rb, spec/requests/sms/sms_console_spec.rb
Added test to ensure SMS test console send button is not disabled after use. Modified view to not disable after use instead of re-enabling after the fact.
=> 9010: Add test to ensure SMS test send button is not disabled after use.

app/javascript/components/Filters/injector.js, app/javascript/components/Filters/utils.js, app/javascript/components/conditions/ConditionSetFormField/utils.js, app/javascript/components/conditions/ConstraintsFormField/ConstraintFormField/injector.js, app/javascript/components/conditions/DisplayLogicFormField/injector.js, app/javascript/components/conditions/SkipLogicFormField/SkipRuleFormField/injector.js, spec/features/forms/form/item_edit_spec.rb
Repro steps:
- Go to a form with multiple groups, including one at the root e.g. https://staging.getelmo.org/en/admin/forms/5e38b7c5-1f04-48f6-95e2-3d0946214abb/edit
- Click to edit the first group
- Close modal, then click to edit second group
- Note the Name field is correct but the Display Logic field is wrong
This fix is a bit hacky, but it's the simplest solution I could think of given the unusual combination of technology we have in this scenario:
- Rails creating a React component
- React component creating a Mobx store
- Same React component being re-created when the modal goes away and comes back, thus needing to re-create the store as well
Reason it wasn't working:
- When the React component was re-created, it asked for an instance of the store, and was given the old instance of …
=> 10267 fix group condition issue [hotfix]

app/assets/stylesheets/local/search/_filters.scss
Fixes CSS ordering issue where select2.css is now imported after application.css so its values took precedence over our customization here.
Note for posterity: staging v9.23.1 does not experience this, so it must have been a change since then. Probably not worth spending more time on since this seems to be the only issue.
=> 10312: Make z-index important, add docs

app/assets/javascripts/views/user_profile_form_view.js.coffee
Fixes a long-standing bug where password fields were hidden if the page refreshed, e.g. when submitting a form that has errors. Previously they were only shown on a change in status of the select dropdown.
=> 10330: Toggle password fields on render

app/assets/javascripts/legacy/views/report/edit_view.js
Styles weren't being changed effectively on https://staging.getelmo.org/en/m/sandboxkevin/reports/new. Fixes:
- Remove `secondary` class when adding `primary`, to prevent style conflicts
- Restore `disabled` attribute when un-enabling
=> 10384 report run btn styles

app/views/responses/answers/_single_editable.html.erb, config/application.rb
Webpacker seems not to include `vendor/assets/` images by default (based on https://stackoverflow.com/a/14195512/763231), this fixes that. Confirmed via:
```bash
NODE_ENV=production RAILS_ENV=production rails assets:precompile
find public/assets -name *.svg
```
The editor icons were working on staging, probably from stale assets... not sure why staging used stale assets and health got cleaned, but images definitely get compiled now locally.
=> 10404 wysiwyg icons

app/assets/javascripts/views/print_form_view.js, app/views/form_items/_printable.html.erb, app/views/forms/_printable.html.erb, spec/features/forms/form/printable_spec.rb, spec/support/helpers/feature_spec_helpers.rb
Changes:
- Fix method call that was renamed
- Wait for load in spec to make sure print page renders without error (this would have caught the original issue)
- Fix incorrect JS date format `2020-0-1` => `2020-01-01`
- Bring specs back from the dead (from https://github.com/thecartercenter/nemo/commit/f562a5c56438a675c72df8ae4435d031fd9818fd) now that they work with updated webdriver
- Clear localstorage to fix flapping spec
=> 10450 fix printable_form show [hotfix]

app/assets/javascripts/app.js, app/assets/javascripts/legacy/controllers/report/report_controller.js, app/assets/javascripts/legacy/views/dashboard.js, app/assets/javascripts/legacy/views/option_set_form.js, app/assets/javascripts/views/dashboard_map_view.js, app/assets/javascripts/views/regenerable_field_view.js
Use `ELMO.unloading` in `beforeunload` to skip XHR error handling when user is navigating. The error can be reproduced on current Firefox, but **not** on current Chrome (navigation errors are gracefully ignored).
- URL to trigger 3s delay + eventual CORS error: `http://slowwly.robertomurray.co.uk/delay/3000/url/https://www.google.com`
- URL to trigger immediate 503: `/ping`
```js
if (xhr.status != 0) // not reliable
if (xhr.readyState < 4) // not reliable
if (!xhr.getAllResponseHeaders()) // not reliable
.on("unload", () => App.unloading = true) // not reliable
.on("unload", () => reqs.each((req) => req.abort())) // track open requests manually
.error((xhr) => setTimeout(() => { handle }, 1000)) // at least error won't happen right away
ajax({ async: false }) // deprecated
```
```json …
```
=> 10449 fix dashboard loading

app/views/layouts/_elmo_form_field.html.erb
I think this was just a little bug that crept in recently. Noticed it on option set form:
=> 10470: Fix inline hint css class application

.eslintrc.yml, app/assets/javascripts/legacy/views/draggable_list.js, app/assets/javascripts/legacy/views/report/edit_view.js, app/assets/javascripts/views/group_modal_view.js, app/assets/javascripts/views/return_to_draft_view.js, app/controllers/qing_groups_controller.rb, app/models/qing_group.rb, app/views/qing_groups/_modal.html.erb, app/views/qing_groups/_modal_body.html.erb, spec/factories/forms.rb, spec/features/forms/form_item/qing_group_form_spec.rb
There are multiple possible "name" fields due to i18n, so they can't be marked "mandatory", and errors won't render automatically above the custom field. So `group_name` errors are bubbled up and rendered as base errors on the form.
There's also a bit of JS cleanup included.
=> 10446 disallow blank group name

app/assets/stylesheets/global/html_forms/elmo_forms/_fields.scss
Changed to fix styles.
Editable (no change here):
Read only (fixed):
=> 10325 style fixes

Gemfile.lock, app/models/o_data/question_type.rb, app/models/o_data/simple_entities.rb, app/models/o_data/simple_entity.rb, app/models/o_data/simple_property.rb, app/models/o_data/simple_schema.rb, app/models/question_type.rb, app/overrides/o_data_controller_override.rb, spec/features/forms/form/printable_spec.rb, spec/fixtures/odata/basic_metadata.xml, spec/fixtures/odata/empty_metadata.xml, spec/fixtures/odata/nested_groups_metadata.xml, spec/requests/api/v1/answers_request_spec.rb, spec/requests/api/v1/responses_request_spec.rb, spec/requests/odata/metadata_spec.rb, spec/requests/odata/root_json_spec.rb, spec/support/contexts/api_context.rb, spec/support/contexts/odata.rb
Companion PR: https://github.com/sassafrastech/odata_server/pull/4
- Override the `/$metadata` schema with our own (much simpler) classes that properly define our hierarchy of nestable groups
- Move `before_action` to the very first action (because later actions depend on the schema already existing)
- Temporarily stub out the resource JSON (awaiting the upcoming PR for 10595), since incorrect data types can break Power BI
As a result of this PR:
- http://nemo.test/en/m/sandbox/odata/v1/
- Now has URL-friendly names like `Responses-7e058345-4526-4ba8-b3ad-2cbf5e49a2b5`
- Old names broke Power BI if they contained colons
- http://nemo.test/en/m/sandbox/odata/v1/$metadata
- Now defines EntityTypes for all groups
- Now specifies accurate types for answer values
- …
=> 10594 odata metadata

Gemfile, Gemfile.lock, config/application.rb
Fixes:
```
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
nemo/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require': dlopen(nemo/vendor/bundle/ruby/2.4.0/gems/eventmachine-1.2.7/lib/rubyeventmachine.bundle, 9): Library not loaded: /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (LoadError)
Referenced from: nemo/vendor/bundle/ruby/2.4.0/gems/eventmachine-1.2.7/lib/rubyeventmachine.bundle
Reason: image not found - nemo/vendor/bundle/ruby/2.4.0/gems/eventmachine-1.2.7/lib/rubyeventmachine.bundle
```
I tried quite a few other suggested workarounds to no avail; this comment did it for me https://github.com/oneclick/rubyinstaller2/issues/96#issuecomment-548249647
=> Explicitly require eventmachine (for homebrew)

.eslintrc.yml, Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/javascripts/views/response_list_view.js, app/assets/javascripts/views/settings_view.js, app/assets/stylesheets/global/_buttons.scss, app/assets/stylesheets/global/html_forms/elmo_forms/_fields.scss, app/assets/stylesheets/local/_settings.scss, app/controllers/responses_controller.rb, app/helpers/elmo_form_builder.rb, app/helpers/responses_helper.rb, app/models/response_o_data_export_options.rb, app/views/responses/_export_csv_modal.html.erb, app/views/responses/_export_odata_modal.html.erb, app/views/responses/index.html.erb, app/views/settings/_external_sql.html.erb, app/views/settings/index.html.erb, config/initializers/inflections.rb, config/locales/en/main.yml, spec/features/responses/csv_export_spec.rb, spec/features/responses/odata_export_spec.rb, spec/support/helpers/feature_spec_helpers.rb
- Added Bootstrap "Export" dropdown to Responses index_links
- Added OData export modal that matches existing UI elements
- Used "Copy to Clipboard" functionality for existing Settings `external_sql`
- Updated elmo form logic so we can easily reuse `:copyable` and `:pre`
=> 10601 odata ui

Gemfile, Gemfile.lock, app/models/user.rb, config/locales/en/main.yml, spec/jobs/tabular_import_operation_job_spec.rb, spec/models/user_import_spec.rb, spec/models/user_spec.rb, spec/requests/basic_authentication_spec.rb
Collect does not yet support sending UTF-8 encoded Basic auth, but [is open to adding support](https://forum.getodk.org/t/support-for-special-characters-in-usernames-basic-auth/27696/4) if we submit a PR. Either way, we should not throw up a 500 error if a username is submitted with invalid encoding.
This PR
1. converts the input to UTF-8 if necessary,
2. allows a broader set of characters to be in the username (specifically `[:word:]` and `.`), and
3. properly returns 401 if the username doesn't exist, regardless of encoding.
Do you agree this is a reasonable route to go? If so, TODO:
=> 10823 fix server 500 with unicode usernames

app/controllers/media/objects_controller.rb, app/models/answer.rb, app/models/forms/integrity_warnings/option_set_warner.rb, app/models/forms/integrity_warnings/question_warner.rb, app/models/forms/integrity_warnings/warner.rb, app/models/o_data/question_type.rb, app/models/o_data/simple_entities.rb, app/models/o_data/simple_property.rb, app/models/results/csv/answer_processor.rb, app/models/results/response_json_generator.rb, app/overrides/o_data_controller_override.rb, config/locales/en/main.yml, lib/tasks/db_create_fake_data.rake, spec/fixtures/odata/basic_metadata.xml, spec/fixtures/odata/empty_metadata.xml, spec/fixtures/odata/nested_groups_metadata.xml, spec/fixtures/response_json/basic.json, spec/fixtures/response_json/repeats.json, spec/models/forms/integrity_warnings/option_set_warner_spec.rb, spec/models/results/response_json_generator_spec.rb
⚠️ May be easier to view individual commits
- Improved types:
- Authenticated media URLs
- Geographic Hash
- Cascading select Hash
- Select multiple array
- Better "warner" info for OptionSets in use, because I needed to find one for testing and this seemed useful!
=> 10704 better odata types

app/models/results/csv/answer_processor.rb, app/models/results/csv/answer_query.rb, spec/fixtures/response_csv/truncated_values.csv, spec/models/results/csv/answer_processor_spec.rb, spec/models/results/csv/generator_spec.rb
Detect `long_text` answers and only truncate those vals. Somehow this was completely overlooked when I originally implemented it and **every** `value` field was truncated 😊 
Will hotfix onto health.
=> 10920: Fix integers missing from truncated CSV export

app/jobs/response_csv_export_operation_job.rb, app/models/operation.rb
When using cloud storage, now instead of rendering a file named `20200729-9391-lk1wg1` in the browser, it downloads a file named `fakemission7718-responses-2020-07-30-0403.csv` as expected.
=> 10958: Set metadata so cloud attachments download properly

app/controllers/welcome_controller.rb
Cache the `location_answers` queries for the map. In practice, reduces GW homepage load time from 6.0 => 0.3 seconds (20x improvement :rocket:)
Real cache key example: `en-response/mission-0a448e11-5959-4362-9e5c-8b92151ed5d6/132-20200813173101-assignment/mission-0a448e11-5959-4362-9e5c-8b92151ed5d6/34-20200813173038-users/8dcd65d0-f624-4845-b1bf-7714edef09cd/location_answers`
=> 10997 map performance

app/assets/javascripts/views/search_form_view.js, app/helpers/forms_helper.rb, app/helpers/reports_helper.rb, app/javascript/components/Filters/__snapshots__/component.test.js.snap, app/javascript/components/Filters/__snapshots__/utils.test.js.snap, app/javascript/components/Filters/component.test.js, app/javascript/components/Filters/utils.js, app/javascript/components/Filters/utils.test.js, app/views/reports/standard_form_report/_full_width_summary_row.html.erb, app/views/reports/standard_form_report/_item.html.erb, config/locales/en/main.yml
Motivation:
- Previously, `page` was not reset when doing a search with the React search filter component. If you were on page 2 and searched for something that only had 1 page of results, you'd see a **blank** page saying e.g. "showing all 8 questions".
Core changes:
- Reset `page` on search
- Clean up messy snapshot tests a bit
Additional tweaks:
- Link to responses using the React search UI (`form-id:`) instead of textbox (`form:`)
- Fix `ActionController::UnknownFormat` when clicking standard from report links to responses
=> 10996 fix blank lists after searching

app/models/option_set.rb, db/migrate/20200817185105_nullify_level_names_for_single_level.rb, db/schema.rb, spec/models/option_set_import_spec.rb
> Looks like this is happening when a single level option set has an option level name defined, which is not a typical scenario (would involve checking the 'multilevel' box filling in the name, then unchecking it). And this shouldn't really even be possible. issue to correct this: "Clear option level names for single-level option sets on save"
Diagnostics:
- The checkbox has been disabled for years, so I'm not sure how this would have happened in the first place: [blame for option_set_form.js](https://github.com/thecartercenter/nemo/blame/cc3b8ec979f7301b4f3e11bd14c3e1ea40b28815/app/assets/javascripts/legacy/views/option_set_form.js#L95)
- Ah, it must be from OptionSet imports! The header was used for `level_names` even if it was single-level
=> 9948 clear level_names on save

app/jobs/cache_o_data_job.rb, docs/delayed-job.service
My goodness, it's a whole new world! Health is caching thousands of responses right now but the web server still runs like nothing is going on. Seriously a huge deal.
- Weights are out of 100 max
- More info: https://unix.stackexchange.com/a/495013/150560
- Docs: https://www.freedesktop.org/software/systemd/man/systemd.resource-control.html
I can roll out this config change to the whole fleet via elmo-deploy if it looks good to you.
---
Hmm, though it worked for performance, it did NOT solve the underlying problem that led to health completely locking up (it happened again several minutes later). Still looking into why.
=> 11083 De-prioritize background jobs to let web stay fast

config/environments/development.rb, config/environments/production.rb, docs/development-setup.md
Large reports were not being cached because they exceeded the memcached limit. Enabling compression makes them ~5-10x smaller in practice, with a minor CPU overhead that seems worthwhile.
Even with compression, many reports will still exceed the default 1 MB memcached limit. We should probably increase that in production via `/etc/memcached.conf`
Proposal:
- `-m 128` (2x the default total memory limit, in MB)
- `-I 16m` (16x the default per-item memory limit -- may as well? We cache relatively few things that are shared by many users, and relatively few reports are actually this big)
Some reports (like LEON "MOY Analysis") uncompressed are **137.4 MB**!! Compressed is 10.1 MB, and data over the wire to the client is 3.6 MB. There's nothing I can think of to speed up ridiculous reports …
=> 11052 report caching

app/models/results/response_json_generator.rb, spec/fixtures/response_json/legacy_new_qings.json, spec/models/results/response_json_generator_spec.rb
It was hard to find conclusive docs; I finally found some context in https://issues.oasis-open.org/browse/ODATA-1071. OData explicitly disallows Collections from being null, requiring that they be empty arrays instead. For Collections, the Nullable attribute applies to its children instead of the property itself.
Hotfixing and re-caching on Secure2 immediately so Zied can use it.
=> 11166 fix OData default value for Collections

app/controllers/password_resets_controller.rb, spec/features/users/password_reset_spec.rb, spec/support/helpers/feature_spec_helpers.rb
Added feature specs. Made login more explicit after successful passwd change.
Hopefully this fixes it!?
=> 5531: Make login more explicit in password reset

.env.development, .env.example, .gitignore, app/overrides/o_data_controller_override.rb, docs/development-setup.md, docs/production-setup.md
Now that settings.local.yml.example is gone, shouldn't we have .env.example for local development with all the old values defaulted there instead? (If I understand correctly, the `nemo-deploy` server will control `.env` on cloud servers so this change is only for local development)
Just trying to understand the migration path. Several things have changed and I don't quite remember what else is coming down the pipe.
=> Add .env.example and document in setup instructions

app/models/report/standard_form_report.rb
Apparently this has broken for at least an olympiad...
The standard report was not marking itself populated properly after running, so the view wasn't rendering itself. Only happened in cases where the report data is sent in the AJAX response rather than after a refresh, when it's run anew.
=> 11177: Fix standard report to mark self populated

app/overrides/o_data_controller_override.rb, spec/requests/odata/resource_spec.rb, spec/support/contexts/o_data.rb
This one came up again. 
There were actually two sources of indeterminate ordering:
1. The order of the responses in the ODataController
2. The order of the responses in the spec itself.
I set up explicit ordering for both. Hopefully this should fix it. @cooperka please note how I did this in the spec, by just storing the responses in a let var instead of saving and reloading them. If doing the latter, you'd need to use an `order` clause, but storing in a let is more efficient anyway.
=> 11300: Set explicit ordering on responses

app/models/o_data/simple_entities.rb, spec/fixtures/odata/basic_metadata.xml, spec/fixtures/odata/empty_metadata.xml, spec/fixtures/odata/nested_groups_metadata.xml
I unintentionally included `LastCached` in metadata during a dev tooling improvement. Removing, otherwise it breaks Power BI if it's not provided in cached legacy data.
The data will still be sent down for debugging purposes, it just won't be listed in the "fields I promise to send you" metadata.
=> 11390 fix OData for Power BI

app/assets/javascripts/views/file_uploader_view.js, config/locales/en/main.yml
Dropzone shows "There was an error uploading the file" when really you just got signed out due to inactivity and need to refresh the page. The user import dropzone in particular requires re-authorization so this happens in a fairly short time window.
Note: the `RECENT_LOGIN_REQUIRED` string is defined in `authorization.rb`
=> 11418: Show better DropZone error message for unauthorized file uploads

app/controllers/forms_controller.rb, app/models/form.rb, spec/models/form_spec.rb
Fixes 2 issues related to ODK formList caching:
- List doesn't update when form name changes
- List doesn't update when you access it via proxy, so the URLs are invalid and it leads to really strange low-level Android bugs in the Collect app. Relevant when debugging locally but would also apply to any regular proxy in production.
=> 11425 fix odk formList caching

app/helpers/option_sets_helper.rb, app/models/form.rb, app/models/option_set.rb, app/models/question.rb, app/models/questioning.rb
I can't believe how simple of a fix this was. Checking existence using count is a bad idea it would appear! Makes sense in retrospect. 
Page loads for forms with lots of responses went from ~5 s to < 1 s.
=> 11474 form page load time

app/assets/stylesheets/local/forms/_printable.scss, app/helpers/application_helper.rb, app/views/forms/_printable.html.erb, app/views/forms/choose_questions.html.erb, app/views/layouts/application.html.erb, app/views/missions/form.html.erb, app/views/operations/show.html.erb, spec/features/forms/form/printable_spec.rb, spec/support/helpers/feature_spec_helpers.rb
I still don't love the way page titles are handled but this cleans things up a bit.
=> 11473: Restore page title on print form and refactor

config/environments/production.rb, lib/config_manager.rb
Fix SMTP by filtering out blank SMTP options. Deployed in branch `release-12.2.1`.
Moved some code around but the only new thing is the `select` filter.
Specs failing due to this reason: https://github.com/thecartercenter/nemo/pull/819#discussion_r594769156
=> 11626: Fix SMTP for password reset

.env, config/initializers/sentry.rb, lib/config_manager.rb
And make the DSN configurable because why not. That also makes it easier to manually disable if users want to.
=> 11593: Don't load Sentry in offline mode

app/controllers/forms_controller.rb, app/decorators/action_links/form_link_builder.rb, app/helpers/icon_helper.rb, app/models/ability.rb, config/locales/en/main.yml, config/routes.rb, spec/models/ability/form_ability_spec.rb
Context: [this Slack thread](https://sassafras.slack.com/archives/C02K5DWP2/p1617997475055600?thread_ts=1617825469.048200&cid=C02K5DWP2) with [this form](https://health.getnemo.org/en/m/malariamonthlyreporting/forms/917d5a48-6d71-4596-96fe-22789bb11683).
Related: I also added a stub server for debugging in https://github.com/thecartercenter/nemo/commit/31cb218c9eb74e9f4eb017bbb9b5f33644c00401.
=> 11713: Add admin feature to re-cache form OData

app/models/o_data/simple_entities.rb, app/models/results/csv/generator.rb, app/models/results/csv/header_map.rb, app/models/results/csv/header_query.rb, spec/fixtures/response_csv/display_logic.csv, spec/models/results/csv/generator_spec.rb
~The main change here is that we now pull in `cached_json.keys` and include those in the CSV header~
^ That didn't actually work for all cases, but what does work is using `form.descendants` to get a list of all questions in the form.
See the spec file I added before and after the second commit to see the user-facing change here -- `IntegerQ2` is now present in the CSV headers even though it was never submitted as an answer (because the display logic hides it).
I will deploy this to the health server after specs pass; we can deploy this to all servers next cycle, no rush.
=> [hotfix] 11830 include conditional qing codes in CSV exports

app/assets/stylesheets/global/_index_tables.scss, app/assets/stylesheets/variables/_mixins.scss, app/decorators/action_links/form_link_builder.rb, app/decorators/action_links/link_builder.rb, app/helpers/icon_helper.rb, app/models/ability.rb, config/locales/en/main.yml, spec/models/ability/form_ability_spec.rb
I do this constantly, in development and production, so this is a nice convenient link for admins:
=> Add admin link to quick-view form responses odata

app/javascript/components/ErrorBoundary/__snapshots__/component.test.js.snap, app/javascript/components/ErrorBoundary/component.js, app/javascript/components/ErrorBoundary/component.test.js, app/javascript/packs/application.js, package.json, yarn.lock
Record errors instead of ignoring them, since we have Sentry installed for Rails already.
This was prompted by Dottie's earlier suggestion that the date filter was disappearing (addressed in #854), which may happen if there's an error in React; until now, we wouldn't have any way to diagnose how frequently this occurs.
=> 11878 Sentry for React

app/models/skip_rule.rb
This was an unfortunate ommission. This code doesn't currently have test coverage because it was always kind of a skunkworks thing. Would be good to add some at some point. It would be interesting since you have to have to separate databases. Or perhaps you could just do the export, blow away the test database mid-test, then import and check. But in any case doing that is beyond the scope of this quick fix.
=> Add clone declaration for SkipRule conditions association

app/assets/stylesheets/global/_layout.scss, app/views/layouts/application.html.erb, config/locales/en/main.yml
Old:
New:
Plus a redundant link to the docs because why not?
=> 12038 changelog link

app/models/utils/xml_packager.rb, spec/models/utils/xml_packager_spec.rb
Tweak to include question code in downloadable response xml.
Now looks like this:
```<code='TextQ2' question='firstname'>Wynn</code='TextQ2' question='firstname'>```
=> 12055: added question code to xml

app/decorators/odk/condition_group_decorator.rb, db/migrate/20211206000000_render_existing_live_forms.rb, db/migrate/20211206000000_render_existing_live_forms2.rb, db/schema.rb
Very simple fix for a very tricky bug (these strings should never actually have been translated using i18n, since they're meant for computers to read).
I have already manually fixed the forms in question by running ODK::FormRenderJob in the server console.
I'm going to hotfix to health right now; let's chat at standup tomorrow about whether this is worth hotfixing to the rest, since it only applies to new standard form copies on missions that have non-english default languages.
=> 12056: Don't translate and/or constraints

app/models/form.rb, spec/models/form_spec.rb
follow-up to #849 (see also notes in https://redmine.sassafras.coop/issues/10826)
=> 12129: prevent underscores in form titles

app/controllers/responses_controller.rb, app/models/odk/response_saver.rb, spec/fixtures/odk/responses/nested_group_form_response_duplicate.xml, spec/models/odk/response_saver_spec.rb, spec/requests/media/odk_response_spec.rb
Several changes:
* Return `:service_unavailable` instead of `:created` when there's a serialization issue, to allow the user to try again momentarily
* Note: we're NOT yet destroying the original response because I couldn't get the specs to reproduce that behavior and I don't want to ship untestable code; we should see if these changes alone resolve the issue
* Increase MAX_TRIES by 20% in case it helps
* Add a random delay in between tries so that different requests can complete in different orders in case this can reduce the frequency of serialization conflicts
* Improve logging
* Add more specs
=> 12143 response serialization improvements

app/decorators/action_links/form_link_builder.rb
Quick win for the servers that have the `NEMO_USE_DATA_FACTORY` env flag set. This helper is called on `forms/new` causing the crash, but only needed on `forms/show`.
=> 12238: Fix crash when trying to create a new form on DF servers

app/models/results/csv/header_map.rb, spec/fixtures/response_csv/multilingual_cascading.csv, spec/fixtures/response_csv/multilingual_cascading_en.csv, spec/models/results/csv/generator_spec.rb
This specific bug was only happening when the user's locale did not match the mission's default locale. Added a couple new specs for similar cases along with the fix.
Will include in this week's release (rather that hotfixing) after specs pass.
=> 12241 fix multilingual multilevel csv export in non-default language

app/controllers/forms_controller.rb, app/decorators/action_links/form_link_builder.rb, app/decorators/application_decorator.rb, app/helpers/forms_helper.rb, app/helpers/icon_helper.rb, config/locales/en/main.yml, config/routes.rb, spec/features/forms/form/form_export_spec.rb
Adds 2 new links:
- export ODK XML for a particular form
- export ODK XML for all published forms (zip file)
Docs: https://getnemo.readthedocs.io/en/latest/content/export/xml.html
=> 12389 export form ODK XML for easier Collect import

config/locales/en/main.yml
Added hint text to specify only letters, numbers, and spaces. these appear to be the only validations
in `app/models/mission.rb`:
```
validates :name, presence: true
validates :name, format: {with: /\A[a-z][a-z0-9 ]*\z/i, message: :let_num_spc_only},
length: {minimum: 3, maximum: 32}, if: proc { |m| m.name.present? }
validate :compact_name_unique
```
=> 8634: Update hint text

app/assets/stylesheets/local/forms/_file_upload.scss, app/views/file_upload/_dropzone_preview.html.erb, spec/support/contexts/file_import.rb
Restyles the upload progress bar area (using flexboxes):
Wraps with flexbox for small screen sizes:
BONUS!: Added an aria-label to the delete icon where there previously was no descriptive text
Additional issue: It is not possible to TAB to the dropzone box to upload a file using keyboard navigation. Setting the tabindex of the dropzone box to 0 is not sufficient as the triggers are on click and on drag, not on keydown. To fix this we would need to listen for keydown.
=> 11469 uploader style

app/assets/javascripts/legacy/views/option_set_form.js, app/controllers/option_sets_controller.rb, config/locales/en/main.yml
Issue: Trying to delete an option node that's in use shows a generic "Server Error" page with no details. 
I added in a check for error code 500, however, I'm not able to figure out how to filter specifically for `ActiveRecord::DeleteRestrictionError`. I think it is because this error comes from Rails but this code is catching errors from ajax, so the only info I can access is from that. Maybe there is a way to get more specific with it?
=> 11090: Add error message for 500 internal server error

app/assets/javascripts/views/form_items_draggable_list_view.js
Follow-up to #950 -- add `isSelf` check to each condition. Otherwise, a question that skips depending on its own answer can never be moved.
=> 7739: Always ignore self-reference

app/decorators/odk/qing_group_decorator.rb
scenario:
- form has a cascading (multilevel) select that's disabled
- DelayedJob tries to render the form to XML automatically
result:
- `undefined method 'body_tags' for nil:NilClass`
fix:
- don't attempt to render non-existent child
note that BOTH the `if` and `else` eventually attempt to use `visible_children[0]`, but they only currently check if there are `children` and not whether the children are visible. this code logic is extremely complex and branching, but the fix here is likely safe.
tested and verified using the prod form linked from the redmine issue (screenshots not uploaded for privacy reasons).
=> 12492: fix rendering to XML if there's a disabled cascading select questioning

app/decorators/odk/form_decorator.rb, app/views/forms/odk/_instances.xml.erb, app/views/forms/show.xml.erb, spec/fixtures/odk/forms/allows_incomplete.xml, spec/fixtures/odk/forms/bilingual.xml, spec/fixtures/odk/forms/conditional_logic.xml, spec/fixtures/odk/forms/default_patterns.xml, spec/fixtures/odk/forms/dynamic_values.xml, spec/fixtures/odk/forms/empty_and_disabled.xml, spec/fixtures/odk/forms/empty_and_hidden.xml, spec/fixtures/odk/forms/grid_group_with_condition.xml, spec/fixtures/odk/forms/media_prompts.xml, spec/fixtures/odk/forms/media_questions.xml, spec/fixtures/odk/forms/multi_screen_gridable.xml, spec/fixtures/odk/forms/multi_screen_group.xml, spec/fixtures/odk/forms/multiscreen_group_with_multilevel.xml, spec/fixtures/odk/forms/nested_group_with_multilevel.xml, spec/fixtures/odk/forms/nested_repeat_group.xml, spec/fixtures/odk/forms/non_repeat_group_with_condition.xml, spec/fixtures/odk/forms/non_repeat_group_with_multilevel_select.xml, spec/fixtures/odk/forms/preload_last_saved.xml, spec/fixtures/odk/forms/repeat_group.xml, spec/fixtures/odk/forms/repeat_group_count.xml, spec/fixtures/odk/forms/repeat_group_count_nested.xml, spec/fixtures/odk/forms/single_screen_repeat_group_with_condition.xml, spec/fixtures/odk/forms/small_large_multilevel.xml, spec/fixtures/odk/forms/standard_copy_with_xpath.xml, spec/fixtures/odk/forms/various_question_types.xml, spec/fixtures/odk/forms/various_selects.xml
to fix ODK Central importing:
tested and verified working after this change.
per the [ODK XForms docs](https://getodk.github.io/xforms-spec/#metadata), this section was missing:
```diff
<model>
<instance>
<data id="asdf" orx:version="123">
<question1/>
<question2/>
+          <orx:meta>
+            <orx:instanceID/>
+          </orx:meta>
</data>
</instance>
</model>
```
note: other meta options include `timeStart`/`timeEnd` (automatic timestamps when the form entry was started/ended), `deviceID`, etc. if we wish to use them in the future.
=> 12494: add new 'meta' section to ODK XML

app/jobs/application_job.rb
if, for example, a form (or other object) is created and then deleted before its associated background job can run, the background job will loudly fail with a server alert and possibly cause the DJ queue to backup until it's manually deleted.
instead, we should skip the job if its target no longer exists. tested and verified locally with a series of different fail cases.
the event is also logged to Sentry for analytics.
=> 12506: discard jobs on ActiveJob::DeserializationError

app/controllers/option_sets_controller.rb, app/models/missing_translation_error.rb, app/models/option_set.rb, config/locales/en/main.yml
Option Set CSV export is silently broken if translations don't exist; loudly fail if there are no OS CSV headers available
=> 12511: loudly fail if there are no Option Set CSV headers available

app/models/forms/export.rb
- The exported XLSForm will now include label columns for all languages specified in the form's mission
- Blank cells will be written when a translation is missing
- Bonus: fixes "end group" and "repeat group" lines not being written if they are at the very end of the form
Example of exported XLSForm imported into ODK Central:
https://github.com/thecartercenter/nemo/assets/4603869/2dace73d-b672-4a7a-b043-ca9b8eb082fc
=> 12527: Add translations to XLSForm export

app/models/forms/export.rb
if a form references 2 different option sets, and the option sets have a duplicate level name, ODK Central will fail to upload the generated XLSForm with the error: `the XLSForm could not be converted: Duplicate column header`
To fix this, we prepend the option set name (which is unique in NEMO) to the level name whenever it's referenced in the XLSForm.
=> 12624: xlsform export bug fix: duplicate column header error 

app/models/forms/export.rb
Uses the [XLSForm appearance column](https://xlsform.org/en/#appearance) to add support for:
-     annotate ("annotated_image" qtype)
-     signature ("signature" qtype)
-     multiline ("long text" question type)
-     draw ("sketch" qtype)
-     counter ("counter" qtype)
=> 12625: xlsform export: add appearance column

app/models/forms/export.rb, spec/models/forms/export_spec.rb
Straightforwardly adds additional columns from NEMO question settings. Notes:
- NEMO allows you to "preload last saved answer as a default" - how is this accomplished in XLSForm? (SEE BELOW) ✅ 
- XLSForm allows you to put in a static value as a repeat count, in NEMO you must reference another question's value. ✅ 
- When uploading media_prompt files, NEMO changes the filename to a string of random numbers (e.g., `675f1bab-7de2-4527-b743-fb204c1ebcf5_media_prompt.png`). We may need to warn users because it may not be trivial to actually locate the files they have previously uploaded in order to transfer them over to the new system. Or, is there a way to locate the original filename? ✅ 
- Media_prompt column is tested and working with audio and image uploads, but i didn't have an .mp4 (only …
=> 12614: XLSForm export: Add default value, repeat count, and media prompt columns

app/models/forms/export.rb
This PR adds XLSForm export support for [naming repeat group instances to help with navigation](https://docs.getodk.org/form-logic/#naming-repeats-to-help-with-navigation). If a NEMO form includes a repeat group with an item name, the export method will now create an inner group whose label is equal to that item name.
=> 12614: XLSForm export: add support for repeat_item_name

config/application.rb, config/initializers/new_framework_defaults_6_1.rb
make progress towards the final upgrade by toggling most of these on; need to wait for the 7.1 config before we can fully switch over the `load_defaults` value.
=> 12659: rails 6.1 defaults
